%(asctime)s %(levelname)s %Internal Server Error: /news/37s %(pathname)s %(exc_info)s
Traceback (most recent call last):
  File "C:\Python_projects\news_portal\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python_projects\news_portal\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Python_projects\news_portal\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python_projects\news_portal\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Python_projects\news_portal\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Python_projects\news_portal\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/posts.html
%(asctime)s %(levelname)s %"GET /news/37 HTTP/1.1" 500 87126s %(pathname)s %(exc_info)s
